### ISSUE TITLE
Development of an API

### ISSUE THREAD

**Issue by robdyke** [sardjv/esr_api#405]
The development of an API implies that you intend to make use of the data to feed systems.

I need to make you aware that this is not permitted.

If you intend to feed ESR data into other systems you need to purchase appropriate interfaces for those purposes.

**Comment by robdyke** [comment]
See [The future of healthcare: our vision for digital, data and technology in health and care](https://www.gov.uk/government/publications/the-future-of-healthcare-our-vision-for-digital-data-and-technology-in-health-and-care/the-future-of-healthcare-our-vision-for-digital-data-and-technology-in-health-and-care#infrastructure-1)

> 1. Infrastructure
> Right now, we have too many systems that don’t talk to each other, often because the contracts we have in place do not adequately specify the standards of interoperability, usability and continual improvement that are needed.

> Our technology infrastructure should allow systems to talk to each other safely and securely, using open standards for data and interoperability so people have confidence that their data is up to date and in the right place, and health and care professionals have access to the information they need to provide care. Interoperable, connected health information in other countries has shown cost-and time-saving benefits, including enhanced care co-ordination and a reduction in unnecessary diagnostic testing. 

> We need to replace legacy architectural decisions to keep up with modern technology.

**Comment by KevinMonk** [comment]
We have a meeting with the ESR team tomorrow. Hopefully appears to be a misunderstanding on their part. Should help to get this resolved.

**Comment by robdyke** [comment]
@KevinMonk picked up the phone.

Fixed #405
