### ISSUE TITLE
Project scope - user data.

### ISSUE THREAD

**Issue by HarvsG** [sardjv/esr_api#419]
Would be within the projects scope to allow users to request their own data?

This would allow developers to create front-ends for ESR.

I am building such an app at the moment and have to parse PDFs downloaded from ESR on device - a real pain.

**Comment by alexrudall** [comment]
Hi, thanks for your interest! Yes, if I understand correctly, that's part of the aim of the project. It would be limited within your own trust's network and need to be according to your own trust's data policies and all applicable regulations. Could you drop us an email at info@sardjv.co.uk and we can discuss further?
